######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 22 14:42:16 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += multiwin.h
SOURCES += main.cpp multiwin.cpp
